-- TOOL_TYPE
INSERT INTO TOOL_TYPE(ID, DESCRIPTION, DAILY_CHARGE_AMOUNT, WEEKDAY_CHARGE, WEEKEND_CHARGE, HOLIDAY_CHARGE)
VALUES(1, 'Ladder', 1.99, TRUE, TRUE, FALSE);

INSERT INTO TOOL_TYPE(ID, DESCRIPTION, DAILY_CHARGE_AMOUNT, WEEKDAY_CHARGE, WEEKEND_CHARGE, HOLIDAY_CHARGE)
VALUES(2, 'Chainsaw', 1.49, TRUE, FALSE, TRUE);

INSERT INTO TOOL_TYPE(ID, DESCRIPTION, DAILY_CHARGE_AMOUNT, WEEKDAY_CHARGE, WEEKEND_CHARGE, HOLIDAY_CHARGE)
VALUES(3, 'Jackhammer', 2.99, TRUE, FALSE, FALSE);

-- TOOL
INSERT INTO TOOL(TOOL_CODE, TOOL_TYPE_ID, BRAND) VALUES('CHNS', 2, 'Stihl');
INSERT INTO TOOL(TOOL_CODE, TOOL_TYPE_ID, BRAND) VALUES('LADW', 1, 'Werner');
INSERT INTO TOOL(TOOL_CODE, TOOL_TYPE_ID, BRAND) VALUES('JAKD', 3, 'DeWalt');
INSERT INTO TOOL(TOOL_CODE, TOOL_TYPE_ID, BRAND) VALUES('JAKR', 3, 'Ridgid');